# config.py
LM_STUDIO_URL = "http://localhost:1234/v1/chat/completions"
KNOWLEDGE_BASE_DIR = "knowledge_base"
DEFAULT_CHUNK_SIZE = 200
DEFAULT_CHUNK_OVERLAP = 50
SIMILARITY_THRESHOLD = 0.4
TOP_K_CHUNKS = 2
LLM_TEMPERATURE = 0.1
LLM_MAX_TOKENS = 500




